### ISSUE TITLE
Breaking change in Apollo 1.5.0

### ISSUE THREAD

**Issue by aj2109** [joel-perry/ApolloCombine#15]
The context parameter added in Apollo 1.5.0 is breaking for this, would it be possible to update for this please as we use this in a few places, would be very helpful. Thank you!

**Comment by joel-perry** [comment]
Hello Adam! Thanks for the heads-up. I don't use Apollo anymore, so I don't stay up on breaking changes as much as I should. I just published a new release (0.7.0) that should fix this. Please let me know if it doesn't.
