### ISSUE TITLE
Watchers end when fetch return an error

### ISSUE THREAD

**Issue by RoryKelly** [joel-perry/ApolloCombine#4]
Watchers end the Publisher when fetch returns an error, they shouldn't.

i.e watcher emits  success -> error -> success

but publisher receives success -> error.

**Comment by MaxDesiatov** [comment]
As far as I understand, a publisher can't publish new values after it's finished, and error on a publisher is one of the ways to finish it. I'm not sure if this is applicable to your case, could you provide a code snippet to elaborate?

**Comment by RoryKelly** [comment]
A Publisher representing watcher should have the type `AnyPublisher<Result<Data, Error>, Never>`. The Apollo watcher api does not stop emitting values on error. I.E

```
 task = configuration.client.watch(query: configuration.query,
                                        cachePolicy: configuration.cachePolicy)
      { [weak self] result in
        switch result {
        case .success(let data):
          _ = self?.subscriber?.receive(data)
          
        case .failure(let error):
          // this is wrong as the Apollo Api may keep emitting Success after this event.
          self?.subscriber?.receive(completion: .failure(error))
        }
      }
```

it should be  

```
 task = configuration.client.watch(query: configuration.query,
                                        cachePolicy: configuration.cachePolicy)
      { [weak self] result in
          _ = self?.subscriber?.receive(result)
      }
```

For example if you are offline and use watcher cache can return `.success` the `.error` as the server fetch will fail, if the unified cache is updated the user will expect another `.success`, with the current code the publisher will stop emitting. 

i.e a watcher is an endless stream not one that terminates on error.

**Comment by MaxDesiatov** [comment]
I'm 100% with you on this one, totally valid point.

**Comment by joel-perry** [comment]
This seems reasonable. I must admit to not using `watch` all that much, so this is not something I have run into. Would this apply to `subscribe`, as well?

**Comment by RoryKelly** [comment]
I would believe so I haven't look at the subscribe wrappers.
