### ISSUE TITLE
ApolloSubscribeSubscription and Combine error type  

### ISSUE THREAD

**Issue by CureleaAndrei** [joel-perry/ApolloCombine#6]
Hi, thanks for the ApolloCombine library, saved me a lot of time. But i have a question, is there any reason why the ApolloSubscribeSubscription doesn't handle error like a ApolloFetchSubscription ? I think is really handy to propagate and handle the errors from Apollo through combine framework instead of returning a Publisher with error type NEVER.

If you need more details please tell me. Thanks again!

**Comment by joel-perry** [comment]
I'm glad you find ApolloCombine useful. I was going to direct you to that discussion. Cheers.
