### ISSUE TITLE
Supporting CocoaPods

### ISSUE THREAD

**Issue by abdelmagied94** [joel-perry/ApolloCombine#7]
There are some projects that installed apollo using Cocoapods so if it installed this package using SPM, it will have another version of apollo dependency. If you don't mind, I could make a PR supporting it.

**Comment by joel-perry** [comment]
Certainly. I am not adept at CocoaPods, so I would appreciate it.

**Comment by abdelmagied94** [comment]
@joel-perry Thank you 🙏 I have already created a [specs file ](https://github.com/abdelmagied94/ApolloCombine/blob/master/ApolloCombine.podspec)in a forked version to be able to use it with my project. This pod isn't published so we can replace my information with yours and publish it. I will need your email to use it.

**Comment by joel-perry** [comment]
Email is joel@joelperry.net. Would you be able to add a section to the README for CocoaPods install?
