### ISSUE TITLE
Bug with version 0.4.0

### ISSUE THREAD

**Issue by AlexeyGorbunov** [joel-perry/ApolloCombine#9]
# Bug report

Hi. After upgrading ApolloCombine to version 0.4.0, an error appears in the PublishersExtensions.
Hope for any help.

# Versions

- ApolloCombine SDK version: 0.4.0
- Xcode version: 12.5
- Swift version: 5

<img width="1440" alt="Снимок экрана 2021-04-27 в 21 53 41" src="https://user-images.githubusercontent.com/33594597/116296925-720e9c00-a7a3-11eb-92eb-11aa8960943c.png">

**Comment by joel-perry** [comment]
Yep. Apollo v0.43.0 added that parameter. I am fixing it right now.

**Comment by AlexeyGorbunov** [comment]
> Yep. Apollo v0.43.0 added that parameter. I am fixing it right now.

Thank you very much for the quick response.

**Comment by joel-perry** [comment]
This is fixed in 0.5.0. Thanks for reaching out.
